spring:
  datasource:
    url: jdbc:postgresql://db:5432/incidents
    username: ${POSTGRES_USER:incidents}
    password: ${POSTGRES_PASSWORD:incidents}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
